import re
from typing import Any

from audit_core import AuditEventType

from app.mcp_clients.document_gateway import (
    list_documents,
    read_document,
    search_documents,
)
from app.schemas.artifacts import ArtifactType
from app.services.artifact_service import create_artifact
from app.services.audit_service import log_audit_event


_AGENT_NAME = "workflow_mapper"
_STEP_PATTERN = re.compile(r"^\s*(?P<sequence>\d+)\.\s+(?P<description>.+?)\s*$")


def generate_workflow_map(run_id: str, workflow_id: str) -> dict[str, Any]:
    log_audit_event(
        run_id=run_id,
        event_type=AuditEventType.agent_started,
        actor=_AGENT_NAME,
        details={"workflow_id": workflow_id},
    )

    documents = list_documents(
        run_id=run_id,
        agent_name=_AGENT_NAME,
        workflow_id=workflow_id,
    )

    steps_document = read_document(
        run_id=run_id,
        agent_name=_AGENT_NAME,
        workflow_id=workflow_id,
        document_id="current_workflow_steps",
    )

    process_document = read_document(
        run_id=run_id,
        agent_name=_AGENT_NAME,
        workflow_id=workflow_id,
        document_id="process_narrative",
    )

    approval_references = search_documents(
        run_id=run_id,
        agent_name=_AGENT_NAME,
        workflow_id=workflow_id,
        query="approval",
    )

    steps = _parse_workflow_steps(steps_document.content)

    content = {
        "workflow_id": workflow_id,
        "title": "Workflow Map",
        "summary": _summarize_process(process_document.content),
        "source_documents": [document.model_dump(mode="json") for document in documents],
        "steps": steps,
        "approval_references": [
            reference.model_dump(mode="json") for reference in approval_references
        ],
        "generation_mode": "deterministic_skeleton",
    }

    artifact = create_artifact(
        run_id=run_id,
        artifact_type=ArtifactType.workflow_map,
        content=content,
    )

    log_audit_event(
        run_id=run_id,
        event_type=AuditEventType.agent_completed,
        actor=_AGENT_NAME,
        details={
            "artifact_id": artifact.artifact_id,
            "artifact_type": artifact.artifact_type.value,
            "step_count": len(steps),
        },
    )

    return artifact.model_dump(mode="json")


def _parse_workflow_steps(content: str) -> list[dict[str, Any]]:
    steps: list[dict[str, Any]] = []

    for line in content.splitlines():
        match = _STEP_PATTERN.match(line)

        if not match:
            continue

        sequence = int(match.group("sequence"))
        description = match.group("description").strip()

        steps.append(
            {
                "step_id": f"step_{sequence}",
                "sequence": sequence,
                "description": description,
                "actor": _infer_actor(description),
                "systems": _infer_systems(description),
                "decision_point": _is_decision_point(description),
                "notes": "Generated by deterministic workflow mapper skeleton.",
            }
        )

    return steps


def _infer_actor(description: str) -> str:
    text = description.lower()

    if "supervisor" in text:
        return "Supervisor"

    if "analyst" in text:
        return "Analyst"

    return "Unspecified"


def _infer_systems(description: str) -> list[str]:
    text = description.lower()
    systems: list[str] = []

    if "source system" in text:
        systems.append("Source system")

    if "spreadsheet" in text:
        systems.append("Tracking spreadsheet")

    if "report" in text:
        systems.append("Reporting process")

    if "status" in text or "notes" in text:
        systems.append("Tracking record")

    return systems


def _is_decision_point(description: str) -> bool:
    text = description.lower()

    decision_terms = [
        "determines",
        "approves",
        "rejects",
        "above the approval threshold",
        "requires",
    ]

    return any(term in text for term in decision_terms)


def _summarize_process(content: str) -> str:
    lines = [line.strip() for line in content.splitlines() if line.strip()]

    for line in lines:
        if not line.startswith("#"):
            return line

    return "No process summary available."