from typing import Any

from audit_core import AuditEventType
from project_mgmt_core import IssueCreationRequest
from project_mgmt_core import create_issue as core_create_issue
from project_mgmt_core.exceptions import ProjectMgmtCoreError

from app.core.config import get_settings
from app.mcp_clients.policy_gateway import check_tool_permission
from app.services.audit_service import log_audit_event


_AGENT_NAME = "implementation_planner"
_TOOL_NAME = "project_mgmt_server.create_issue"


class ProjectMgmtGatewayError(Exception):
    """Raised when a project management write action fails."""


def create_issue_from_backlog_item(
    run_id: str,
    backlog_item: dict[str, Any],
    approval_reference: str,
    labels: list[str],
    dry_run: bool = True,
) -> dict[str, Any]:
    permission = check_tool_permission(
        run_id=run_id,
        requesting_agent_name=_AGENT_NAME,
        target_tool_name=_TOOL_NAME,
        approval_granted=True,
    )

    if permission.decision.value != "allow":
        raise ProjectMgmtGatewayError(permission.rationale)

    request = IssueCreationRequest(
        title=backlog_item["title"],
        body=_build_issue_body(
            backlog_item=backlog_item,
            approval_reference=approval_reference,
        ),
        labels=labels,
        approval_granted=True,
        approval_reference=approval_reference,
        dry_run=dry_run,
    )

    settings = get_settings()

    try:
        result = core_create_issue(
            request=request,
            github_token=settings.github_token,
            github_owner=settings.github_owner,
            github_repo=settings.github_repo,
        )
    except ProjectMgmtCoreError as exc:
        log_audit_event(
            run_id=run_id,
            event_type=AuditEventType.write_action_failed,
            actor=_AGENT_NAME,
            details={
                "tool_name": _TOOL_NAME,
                "backlog_id": backlog_item.get("backlog_id"),
                "approval_reference": approval_reference,
                "dry_run": dry_run,
                "error": str(exc),
            },
        )

        raise ProjectMgmtGatewayError(str(exc)) from exc

    log_audit_event(
        run_id=run_id,
        event_type=AuditEventType.write_action_executed,
        actor=_AGENT_NAME,
        details={
            "tool_name": _TOOL_NAME,
            "backlog_id": backlog_item.get("backlog_id"),
            "approval_reference": approval_reference,
            "dry_run": result.dry_run,
            "status": result.status,
            "issue_number": result.issue_number,
            "issue_url": result.issue_url,
        },
    )

    return result.model_dump(mode="json")


def _build_issue_body(
    backlog_item: dict[str, Any],
    approval_reference: str,
) -> str:
    source_risk_ids = ", ".join(backlog_item.get("source_risk_ids", [])) or "None"
    source_control_ids = ", ".join(backlog_item.get("source_control_ids", [])) or "None"

    return f"""## Summary

{backlog_item.get("description", "No description provided.")}

## Implementation Type

{backlog_item.get("implementation_type", "unspecified")}

## Priority

{backlog_item.get("priority", "unspecified")}

## Recommended Owner

{backlog_item.get("recommended_owner", "unspecified")}

## Source Risks

{source_risk_ids}

## Source Controls

{source_control_ids}

## Approval

Approval reference: {approval_reference}

## Generated By

AgentOps Readiness Console implementation planner.
"""