import json
from pathlib import Path
from typing import Any


EXAMPLE_DIRS = [
    Path("examples/payment_reconciliation_outputs"),
    Path("examples/customer_onboarding_outputs"),
]

OUTPUT_PATH = Path("examples/README.md")


def main() -> None:
    sections = [
        "# Example Workflow Outputs",
        "",
        "This folder contains checked-in example outputs generated by the AgentOps Readiness Console.",
        "",
        "The examples demonstrate that the system can evaluate more than one workflow packet and produce governed artifacts, approval-gated backlog behavior, and audit evidence.",
        "",
        "## Included Use Cases",
        "",
    ]

    for example_dir in EXAMPLE_DIRS:
        sections.extend(_build_use_case_section(example_dir))
        sections.append("")

    sections.extend(
        [
            "## What These Examples Prove",
            "",
            "These examples show the full governed workflow pattern:",
            "",
            "```text",
            "Workflow packet",
            "  → workflow map",
            "  → data sensitivity report",
            "  → risk/control matrix",
            "  → HITL design",
            "  → implementation backlog",
            "  → human approval",
            "  → policy-checked write action",
            "  → audit evidence",
            "```",
            "",
            "The payment reconciliation example demonstrates a finance/operations workflow.",
            "",
            "The customer onboarding example demonstrates a SaaS/customer-operations workflow with different risk patterns, including onboarding-specific risks around customer-facing commitments, implementation scope, integrations, handoffs, and timelines.",
            "",
            "To regenerate outputs:",
            "",
            "```bash",
            "PYTHONPATH=services/api python -m scripts.export_example_outputs --workflow-id payment_reconciliation --output-dir examples/payment_reconciliation_outputs",
            "PYTHONPATH=services/api python -m scripts.export_example_outputs --workflow-id customer_onboarding --output-dir examples/customer_onboarding_outputs",
            "```",
            "",
            "To validate checked-in outputs:",
            "",
            "```bash",
            "PYTHONPATH=services/api python -m scripts.validate_example_outputs",
            "```",
            "",
        ]
    )

    OUTPUT_PATH.write_text("\n".join(sections), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


def _build_use_case_section(example_dir: Path) -> list[str]:
    run_response = _read_json(example_dir / "run_response.json")
    risk_matrix = _read_json(example_dir / "risk_control_matrix.json")
    hitl_design = _read_json(example_dir / "hitl_design.json")
    backlog = _read_json(example_dir / "implementation_backlog.json")
    audit_summary = _read_json(example_dir / "audit_summary.json")
    approval_response = _read_json(example_dir / "approval_response.json")

    workflow_id = run_response["workflow_id"]
    title = workflow_id.replace("_", " ").title()

    risk_summary = risk_matrix["content"]["summary"]
    hitl_summary = hitl_design["content"]["summary"]
    backlog_summary = backlog["content"]["summary"]

    risk_ids = sorted(_collect_risk_ids(risk_matrix))
    backlog_items = backlog["content"]["backlog_items"]

    lines = [
        f"## {title}",
        "",
        f"Output folder: `{example_dir}`",
        "",
        "### Summary",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Risk matrix rows | {risk_summary['row_count']} |",
        f"| Total risks | {risk_summary['risk_count']} |",
        f"| High-severity risks | {risk_summary['high_severity_risk_count']} |",
        f"| Controls referenced | {risk_summary['control_count']} |",
        f"| Approval gates | {hitl_summary['approval_gate_count']} |",
        f"| Review queues | {hitl_summary['review_queue_count']} |",
        f"| Escalation rules | {hitl_summary['escalation_rule_count']} |",
        f"| Backlog items | {backlog_summary['backlog_item_count']} |",
        f"| Approved backlog items | {backlog_summary['approved_count']} |",
        f"| Audit events | {audit_summary['audit_event_count']} |",
        "",
        "### Risk IDs",
        "",
    ]

    for risk_id in risk_ids:
        lines.append(f"- `{risk_id}`")

    lines.extend(
        [
            "",
            "### Backlog Items",
            "",
        ]
    )

    for item in backlog_items:
        status = item.get("status", "unknown")
        priority = item.get("priority", "unknown")
        lines.append(f"- **{item['title']}**")
        lines.append(f"  - ID: `{item['backlog_id']}`")
        lines.append(f"  - Priority: `{priority}`")
        lines.append(f"  - Status: `{status}`")
        lines.append(f"  - Type: `{item['implementation_type']}`")

    lines.extend(
        [
            "",
            "### Approval / Audit Proof",
            "",
            f"- Approval response status: `{approval_response['status']}`",
            f"- Dry run: `{approval_response['dry_run']}`",
            f"- Issue creation result: `{approval_response['issue_creation_result']['status']}`",
            f"- Contains approval event: `{audit_summary['contains_approval_event']}`",
            f"- Contains write-action event: `{audit_summary['contains_write_action_event']}`",
            "",
        ]
    )

    return lines


def _collect_risk_ids(risk_matrix: dict[str, Any]) -> set[str]:
    risk_ids: set[str] = set()

    for row in risk_matrix["content"]["matrix_rows"]:
        for risk in row.get("identified_risks", []):
            risk_ids.add(risk["risk_id"])

    return risk_ids


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()